### ISSUE TITLE
Graphic on homepage

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#177]
Section 1 (Show Your Skills Challenges)
The graphic of the badge on the left seems off its desired position - too low. Can we move it up some

- [x] done

**Comment by dmessing** [comment]
@callmekatootie can you double check this one in the latest still seems a little off

**Comment by callmekatootie** [comment]
On it.

**Comment by callmekatootie** [comment]
Fixes are in https://github.com/appirio-tech/ap-lime-topcoder/pull/191

**Comment by Wippirio** [comment]
@dmessing close
