### ISSUE TITLE
On the badges page

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#180]
Add the standard “Ready to Stand Out in the Crowd?” section with the “Become a member” button when viewing the page in unauthenticated session at the bottom?  This is the same on the landing page
- [ ] done

**Comment by callmekatootie** [comment]
Note that here you will have "Ready to Stand out in the Crowd" text twice - one at the top and one at the bottom.

**Comment by callmekatootie** [comment]
Ah - just saw #186. Ignore above comment.

**Comment by Wippirio** [comment]
@dmessing close
