### ISSUE TITLE
Detailed FAQ Page -- fix bottom footer

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#181]
Can we fix the size and font of the text to match the home page footer?  Should be $heather-gray and the appropriate size.

- [ ] done

**Comment by callmekatootie** [comment]
Can you provide more details - the footer is common across all pages and should look the same. Perhaps a snapshot to describe?

**Comment by dmessing** [comment]
Just on the far page sorry.  The text is back and should be grey above the Blue button see how it doesn't match the home page bottom? I will get exact text

**Comment by callmekatootie** [comment]
Understood what element you are talking about. Fixed it and pushed the changes into the Pull Request.

**Comment by Wippirio** [comment]
@dmessing: just had a hangout about this one. Also, the Swiftoberfest challenges page seems broken now in its header.

**Comment by Wippirio** [comment]
@dmessing close
