### ISSUE TITLE
Swiftoberfest page add image for leaderboard

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#182]
I've attached the image

- [ ] done

![leaderboard-coming-soon](https://cloud.githubusercontent.com/assets/664840/10179440/f364aa40-66d3-11e5-8c89-dd5b387ff861.png)

**Comment by dmessing** [comment]
The above graphic might need to be sized appropriately too

**Comment by callmekatootie** [comment]
Just mentioning here that the leaderboard section was commented and I uncommented it and placed the image in the section. Let me know if that is not what you asked for.

**Comment by Wippirio** [comment]
Looks good on QA
@dmessing close
