### ISSUE TITLE
Add badge from home page on Start competing

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#184]
Move the logic from the sign up for participant badge button to the start competing button for logged in members on the landing page.

We are **not** removing this logic from the learn page but just duplicating it.  

We don't have to worry about showing error state, but just redirect to /challenges/all when it is successful.

- [ ] implemented

**Comment by callmekatootie** [comment]
I am sorry but I do not follow. You speak of home, learn and badge pages here but I am confused.

Can you show a snapshot?

**Comment by Wippirio** [comment]
@dmessing, is this right? I don't remember asking for a third button in the top section.

**Comment by callmekatootie** [comment]
@Wippirio Yikes. That would be my bad. I added that code for testing purposes but forgot to remove it. Hang on, fixing it...

**Comment by callmekatootie** [comment]
@dmessing Created PR here - https://github.com/appirio-tech/ap-lime-topcoder/pull/195
This should hide the third button which will show up only on login - just as before

**Comment by Wippirio** [comment]
@dmessing close
