### ISSUE TITLE
fix leaderboard text points should be 100,90, etc

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#188]
Compete in real-world Swiftoberfest challenges for your chance to earn Swiftoberfest leaderboard points. In addition to any cash earnings, members who pass review and finish in the top 10 places for any given challenge will earn leaderboard points. The first place finisher receives 100 points, second place receives 90 points, and so on down to 10 points for 10th place and beyond. The more challenges you compete in, and the more entries you have that pass review, the more leaderboard points you’ll receive and the better your chances of winning Swiftoberfest prizes! 

- [ ] done

**Comment by dmessing** [comment]
Close

**Comment by Wippirio** [comment]
@dmessing close
