### ISSUE TITLE
Swiftoberfest Leaderboard Contest Rules Button

### ISSUE THREAD

**Issue by Wippirio** [appirio-tech/ap-lime-topcoder#216]
In the Leaderboard section of the Swiftoberfest page, the Contest Rules should be a link (like View Challenges) rather than a button (like Become a Member)

**Comment by cwdcwd** [comment]
Challenge created successfully
Status:Draft
Challenge Url: https://www.topcoder-dev.com/challenge-details/30049591/?type=develop&noncache=true
Forum Url: https://apps.topcoder-dev.com/forums/?module=Category&categoryID=28517
