### ISSUE TITLE
Create new registration page

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#227]
We need a separate registration landing page for Google AdWords campaigns. See this doc for copy and layout:

https://docs.google.com/document/d/1lww02uC7CEma9vzZdLoS94B8ZDzioD8NOfsSLlnNz6w/edit

@callmekatootie

**Comment by callmekatootie** [comment]
Requested access for the provided doc. Kindly grant access.

**Comment by callmekatootie** [comment]
Received access. Thanks.

When should this page load? I mean, what should the URL be for the user to see the mentioned page instead of the existing registration page?

**Comment by dmessing** [comment]
This is a stand alone page it won't be linked, it will be linked to via ads

**Comment by callmekatootie** [comment]
Ok - So the styling should be a white background paragraph on the left with a black background form on the right?

**Comment by callmekatootie** [comment]
I proceeded with the existing background itself. Made it easier to carry it out. Let me know if it looks fine.
