### ISSUE TITLE
Better tracking of UTM codes

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#228]
As we rollout campaigns to drive iOS Community membership, we're using UTM codes in links to the site. However, if a user navigates away from the first page they hit the UTM codes don't persist in the URL, and when they eventually register we don't capture values for Medium, Source, and Campaign.

For example, link points to: http://ios.topcoder.com/register?utm_medium=cpc&utm_source=google&campaign=swiftoberfest

User clicks on the link and hits the register page, but navigates around the site before eventually registering. The UTM codes are cookied and continue to be reported by Google Analytics, but the member database doesn't capture the UTM values from the original link.

@callmekatootie

**Comment by callmekatootie** [comment]
Understood. So if the user moves to the Home page - you still want the utm_* query parameters to exist in the URL.

Note that the solution that I have in mind is to persist the query parameters in general - let me know if you want this to be specific to utm_* - basically, if a new query param called foobar appears tomorrow, it will remain across all urls just like utm_*

**Comment by callmekatootie** [comment]
Read the other ticket - So, during registration, if registration is successful, I will be removing the utm_* params from the URL - is that still required after registration?

**Comment by dmessing** [comment]
Your first comment is correct.  You don't have to worry about removing the parameters

**Comment by callmekatootie** [comment]
Got it. Thanks.
