### ISSUE TITLE
Fix sweepstakes page

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/ap-lime-topcoder#230]
We need to add a section to announce the upcoming sweepstakes and eventually announce the winners of the previous. Details in the attached PDF

[Sweepstakes webpage (1).pdf](https://github.com/appirio-tech/ap-lime-topcoder/files/11890/Sweepstakes.webpage.1.pdf)

@callmekatootie

**Comment by callmekatootie** [comment]
Is this the image that I will be using (picked it off the badges page): http://ios.topcoder.com/content/images/svg/Show-Your-Skills-06.ab608bb5.svg

It does not have the text "iOS Ready / Swift Ready" at the bottom though.

Also - the section goes into the "About Swiftoberfest" page? If so, where should it be placed? I mean below which existing section?

**Comment by dmessing** [comment]
This goes into the leaderboard section.  The blue section.  The PDF should show the image.

**Comment by callmekatootie** [comment]
Oh, in the same section? Ok.

About the image - yes the PDF does contain it - I assume you would want me to slice it but can you check with the original designer if they have the original image with them - I am sure it will be a 5 minute job for them as opposed to my 30 mins to get the image sliced.
